.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. jfkbitcoin1776_qt test_jfkbitcoin1776_qt
clean: FORCE
	$(MAKE) -C .. jfkbitcoin1776_qt_clean test_jfkbitcoin1776_qt_clean
check: FORCE
	$(MAKE) -C .. test_jfkbitcoin1776_qt_check
jfkbitcoin1776-qt jfkbitcoin1776-qt.exe: FORCE
	 $(MAKE) -C .. jfkbitcoin1776_qt
